name: test_auth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  algolia: ^1.1.1
  any_link_preview: ^2.0.9
  app_settings: ^4.1.8
  async: ^2.9.0
  badges: ^2.0.3
  build_runner: ^2.2.0
  cached_network_image: ^3.2.1
  camera: ^0.10.0
  carousel_slider: ^4.1.1
  chewie: ^1.3.5
  cloud_firestore: ^3.5.0
  cloud_functions: ^3.3.5
  connectivity_plus: ^2.3.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  device_info_plus: ^4.1.2
  emoji_picker_flutter: ^1.3.0
  file_picker: ^5.2.1
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  firebase_core_platform_interface: ^4.5.0
  firebase_messaging: ^13.0.2
  firebase_storage: ^10.3.9
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_chat_ui: ^1.6.6
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.3.0
  flutter_layout_grid: ^2.0.1
  flutter_markdown: ^0.6.12
  flutter_no_internet_widget: ^0.0.8+16
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutterfire_ui: ^0.4.3+12
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  gallery_saver: ^2.3.2
  galleryimage: ^1.2.0
  geocoding: ^2.0.5
  geoflutterfire: ^3.0.3
  georange: ^1.0.0
  go_router: ^5.0.5
  google_maps_flutter: ^2.2.0
  google_ml_vision: ^0.0.7
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  image: ^3.2.2
  image_input_field:
    path: packages/image_input_field
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  linkify: ^4.1.0
  location: ^4.4.0
  mocktail: ^0.3.0
  overlay_support: ^2.0.1
  palette_generator: ^0.3.3+1
  path: ^1.8.1
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pinput: ^2.2.11
  rx: ^0.1.3
  rxdart: ^0.27.7
  settings_ui: ^2.0.2
  share_plus: ^4.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1
  tflite:
    path: packages/my_tflite
  timeago: ^3.2.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  video_player: ^2.4.7

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/ml/image_classification/mobilenet.tflite
    - assets/ml/image_classification/labels.txt
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
