// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class TestAuthFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtnrHjuuSdVR_dDJ8AXMkkpiwqZQvW_8',
    appId: '1:162228522621:web:8df308ec2d1b27203eab14',
    messagingSenderId: '162228522621',
    projectId: 'test-auth-72ce8',
    authDomain: 'test-auth-72ce8.firebaseapp.com',
    storageBucket: 'test-auth-72ce8.appspot.com',
    measurementId: 'G-LZF45HFFQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBL3qoqwBpnB-L2k4JvIT0atM-3XjZMQ',
    appId: '1:162228522621:android:f6be41d667590db93eab14',
    messagingSenderId: '162228522621',
    projectId: 'test-auth-72ce8',
    storageBucket: 'test-auth-72ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4JJk_L3dMoEyH7IRlGqD4FaLkm32XQo',
    appId: '1:162228522621:ios:67b4352e32ef90413eab14',
    messagingSenderId: '162228522621',
    projectId: 'test-auth-72ce8',
    storageBucket: 'test-auth-72ce8.appspot.com',
    androidClientId:
        '162228522621-i0lp9mdi85mcvdtgrl6tr5v72nn45uuk.apps.googleusercontent.com',
    iosClientId:
        '162228522621-cstlsjgic9547uq8b7h5sm9p0gpjiiia.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4JJk_L3dMoEyH7IRlGqD4FaLkm32XQo',
    appId: '1:162228522621:ios:67b4352e32ef90413eab14',
    messagingSenderId: '162228522621',
    projectId: 'test-auth-72ce8',
    storageBucket: 'test-auth-72ce8.appspot.com',
    androidClientId:
        '162228522621-i0lp9mdi85mcvdtgrl6tr5v72nn45uuk.apps.googleusercontent.com',
    iosClientId:
        '162228522621-cstlsjgic9547uq8b7h5sm9p0gpjiiia.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAuth',
  );
}
